### ISSUE TITLE
-f option shown in examples when it should be a -d

### ISSUE THREAD

**Issue by AmNe5iA** [mdawsonuk/LevelDBDumper#1]
LevelDB Dumper 2.0.0.0

Author: Matt Dawson

        d               Directory to recursively process. This is required.
        q               Don't output all key/value pairs to console. Default will output all key/value pairs
        csv             Directory to save CSV formatted results to. Be sure to include the full path in double quotes

Examples: LevelDBParser.exe **-f** "C:\Temp\leveldb"
          LevelDBParser.exe **-f** "C:\Temp\leveldb" --csv "C:\Temp" -q

          Short options (single letter) are prefixed with a single dash. Long commands are prefixed with two dashes

**Comment by mdawsonuk** [comment]
Thanks for that - I've fixed the issue now and pushed a new release
