### ISSUE TITLE
LevelDBDumper does not produce output files

### ISSUE THREAD

**Issue by SolitudePy** [mdawsonuk/LevelDBDumper#12]
**LevelDB Dumper version**

v2.0.2 latest

**Describe the bug**

When running LevelDBDumper it does not produce the output files as expected. 
The following command: 

`LevelDBDumper.exe -d C:\Temp\leveldb ` 

**indeed produce output to the terminal, but any of the following commands:**

`LevelDBDumper.exe -d C:\Temp\leveldb -o C:\Temp`
`LevelDBDumper.exe -d C:\Temp\leveldb -o C:\Temp --outputFile evidence.csv`

Simply does not create any files. I also tried the Kape module of LevelDBDumper and the same happened.
I tried on both Whatsapp & Discord leveldb files and the same happened.

**To Reproduce**

Simply running LevelDBDumper on Discord/Whatsapp leveldbs

**Expected behavior**

Evidence files created at output directory

**Comment by SolitudePy** [comment]
Oh, I suppose the release tagged with latest v2.0.2 is broken? should I use the pre-release of v3.0.0?

**Comment by mdawsonuk** [comment]
> Oh, I tried the pre-release of v3.0.0 LevelDBDumper and it works as expected. I suggest you organize the releases because the latest one is broken 

Hi, please could you give it a go with 3.0.0, I need to get that officially released, thanks for the reminder.

**Comment by SolitudePy** [comment]
Yeah as I wrote I tried v3.0.0 and it worked as expected
