### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by wearyexcellance** [mdawsonuk/LevelDBDumper#3]
Hi, i'm not getting any output file (neither json nor csv)

**Comment by mdawsonuk** [comment]
> Hi, i'm not getting any output file (neither json nor csv)

Hey thanks for reaching out. Could you provide the command you're using to try and get output (suitably redacted if needed)?

**Comment by wearyexcellance** [comment]
LeveLDBParser.exe -d "C:\Users\ASUS\Desktop\leveldb" -o "C:\Temp" -q
Entire functions has no output

**Comment by AJolly** [comment]
Came here to report the same thing - its because github shows v2.0.2 as the latest release.

**Comment by mdawsonuk** [comment]
> Came here to report the same thing - its because github shows v2.0.2 as the latest release.

Thanks - I somehow hadn't noticed that... I need to get around to clearing the backlog of issues and releasing v3, thanks for the reminder
